# Generated by Django 2.0.6 on 2019-05-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAdd',
            fields=[
                ('add_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('addr', models.CharField(blank=True, max_length=20, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_add',
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('book_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('writer', models.CharField(blank=True, max_length=64, null=True)),
                ('press', models.CharField(blank=True, max_length=128, null=True)),
                ('publicaion_time', models.DateField(blank=True, null=True)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('printing_time', models.CharField(blank=True, max_length=20, null=True)),
                ('impression', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=64, null=True)),
                ('words', models.CharField(blank=True, max_length=64, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('paper', models.CharField(blank=True, max_length=64, null=True)),
                ('package', models.CharField(blank=True, max_length=64, null=True)),
                ('book_name', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('dprice', models.IntegerField(blank=True, null=True)),
                ('recommed', models.CharField(blank=True, max_length=2000, null=True)),
                ('content_introduction', models.CharField(blank=True, max_length=2000, null=True)),
                ('author_introduction', models.CharField(blank=True, max_length=2000, null=True)),
                ('menu', models.CharField(blank=True, max_length=2000, null=True)),
                ('review', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.CharField(blank=True, max_length=2000, null=True)),
                ('image_path', models.CharField(blank=True, max_length=2000, null=True)),
                ('serise_name', models.CharField(blank=True, max_length=128, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('shelves_date', models.DateField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('book_status', models.IntegerField(blank=True, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='TClass',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('class_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_class',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('ord_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('num', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_email', models.CharField(blank=True, max_length=20, null=True)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('use_password', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='TUser2',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('class_name', models.CharField(blank=True, max_length=20, null=True)),
                ('counts', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_user2',
            },
        ),
        migrations.CreateModel(
            name='TVerify',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_number', models.CharField(blank=True, max_length=20, null=True)),
                ('subtotal', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_verify',
            },
        ),
    ]
